Repository CSE-110-FA24-Team-17/SleepBuddies, pull requests merged in 2024-11, with the labels that each got.

#17 Adds CodeQL Badge
  README.md
Labels: documentation

#16 Git Attributes and LFS
  .gitattributes
Labels: documentation

#18 Main Page
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/assets/clock.svg
  client/src/assets/meditation.svg
  client/src/assets/moon-sleep.svg
  client/src/components/elements/Alarm.tsx
  client/src/components/elements/Meditation.tsx
  client/src/components/elements/Sleep.tsx
  client/src/components/pages/alarm.tsx
  client/src/components/pages/home.tsx
  client/src/components/pages/meditation.tsx
  client/src/components/pages/sleep.tsx
  client/src/css/App.css
  client/src/css/applet.css
  client/src/css/home.css
  client/src/css/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
  server/README.md
  sleepbuddies/public/logo192.png
  sleepbuddies/public/logo512.png
  sleepbuddies/src/App.css
  sleepbuddies/src/App.tsx
  sleepbuddies/src/index.css
Labels: enhancement

#23 Remove old files
  sleepbuddies/public/logo192.png
Labels: bug

#24 finish welcome, login, and sign up pages
  client/src/App.tsx
  client/src/components/pages/login.tsx
  client/src/components/pages/signup.tsx
  client/src/components/pages/welcome.tsx
  client/src/css/login.css
  client/src/css/signup.css
Labels: enhancement, Work In Progress

#28 Delete sleepbuddies/public/logo512.png
  sleepbuddies/public/logo512.png
Labels: optimization

#29 Music Button
  client/src/App.tsx
  client/src/assets/music.svg
  client/src/components/elements/Meditation.tsx
  client/src/components/elements/Music.tsx
  client/src/components/pages/home.tsx
  client/src/components/pages/music.tsx
  client/src/css/home.css
Labels: enhancement, Work In Progress

#37 Adds Github Testing
  .github/workflows/build_test_react.yml
  client/src/App.test.tsx
Labels: tests

#38 Fixes the github tests
  .github/workflows/build_test_react.yml
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/elements/SleepAnalytics/Chart.tsx
  client/src/components/pages/alarm.tsx
  client/src/components/pages/meditation.tsx
  client/src/components/pages/sleep.tsx
  client/src/components/pages/welcome.tsx
  client/src/css/index.css
  client/src/css/meditation.css
  client/src/index.tsx
Labels: optimization, tests

#39 Set up backend
  .gitignore
  client/package-lock.json
  client/package.json
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/createTable.ts
  server/src/index.ts
  server/tsconfig.json
Labels: enhancement, security

#36 completed welcome, login, and signup page
  client/src/App.tsx
  client/src/components/elements/Login.tsx
  client/src/components/elements/Signup.tsx
  client/src/components/pages/login.tsx
  client/src/components/pages/signup.tsx
  client/src/components/pages/welcome.tsx
  client/src/css/login.css
  client/src/css/signup.css
  client/src/css/welcome.css
Labels: enhancement

#43 Updated Alarm Page
  client/public/alarm-bear.jpg
  client/src/components/elements/AlarmModal.tsx
  client/src/components/pages/alarm.tsx
  client/src/css/AlarmModal.css
  client/src/css/alarm.css
Labels: enhancement

#41 Worked on sleep statistics by adding an interface for users to input …
  client/package-lock.json
  client/package.json
  client/src/components/elements/SleepAnalytics/Chart.tsx
  client/src/components/elements/SleepAnalytics/Graph.tsx
  client/src/components/elements/SleepAnalytics/Statistics.test.tsx
  client/src/components/elements/SleepAnalytics/Statistics.tsx
  client/src/components/pages/sleep.tsx
  client/src/css/Sleep.css
Labels: enhancement

#50 finalized design, testers for welcome page, icon, headings
  client/public/favicon.ico
  client/public/favicon_test.ico
  client/src/App.tsx
  client/src/assets/clock.svg
  client/src/assets/meditation.svg
  client/src/components/pages/alarm.tsx
  client/src/components/pages/home.tsx
  client/src/components/pages/login.tsx
  client/src/components/pages/meditation.tsx
  client/src/components/pages/music.tsx
  client/src/components/pages/signup.tsx
  client/src/components/pages/sleep.tsx
  client/src/components/pages/welcome.tsx
  client/src/css/App.css
  client/src/css/login.css
  client/src/css/signup.css
  client/src/css/welcome.css
  client/src/tests/welcome.test.tsx
  package-lock.json
  package.json
Labels: enhancement, tests
