Repository CSE-110-FA24-Team-17/SleepBuddies, pull requests merged in 2024-12, with the labels that each got.

#55 User Account and Password
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/constants/constants.tsx
  client/src/components/elements/Home.tsx
  client/src/components/pages/login.tsx
  client/src/components/pages/meditation.tsx
  client/src/components/pages/signup.tsx
  client/src/components/pages/welcome.tsx
  client/src/components/utils/encryption.tsx
  client/src/components/utils/user-utils.tsx
  client/src/tests/App.test.tsx
  server/src/createTable.ts
  server/src/index.ts
  server/src/utils/generateHash.ts
Labels: enhancement, needs review

#61 fixed meditation page and added different styles and did journal page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/calm.webp
  client/src/assets/forest.webp
  client/src/assets/journal.svg
  client/src/assets/nature.webp
  client/src/assets/night.webp
  client/src/assets/serenity.webp
  client/src/assets/sunrise.webp
  client/src/assets/water1.webp
  client/src/components/elements/Journal.tsx
  client/src/components/pages/home.tsx
  client/src/components/pages/journal.tsx
  client/src/components/pages/meditation.tsx
  client/src/css/journal.css
  client/src/css/meditation.css
  server/src/index.ts
Labels: enhancement

#58 Alarm Page Update
  client/package-lock.json
  client/package.json
  client/public/daybreak_iphone_alarm.mp3
  client/src/components/elements/Alarm.tsx
  client/src/components/elements/AlarmItem.tsx
  client/src/components/elements/AlarmList.tsx
  client/src/components/elements/AlarmModal.jsx
  client/src/components/elements/AlarmModal.tsx
  client/src/components/elements/AlarmRingingModal.tsx
  client/src/components/pages/alarm.tsx
  client/src/css/AlarmModal.css
  client/src/css/AlarmRingingModal.css
  client/src/css/alarm.css
Labels: enhancement

#66 Fixes account created bug
  client/src/components/pages/signup.tsx
  server/package-lock.json
  server/package.json
  server/src/index.ts
Labels: bug, security, needs review

#67 Enhancement to Alarm Page + Backend
  client/src/components/elements/AlarmItem.tsx
  client/src/components/elements/AlarmList.tsx
  client/src/components/elements/AlarmModal.tsx
  client/src/components/pages/alarm.tsx
  client/src/css/alarm.css
  client/src/tests/Alarm.test.tsx
Labels: enhancement

#59 navigation bar, sleep buddy on home page, updated tos
  client/src/App.tsx
  client/src/assets/AfternoonSB.png
  client/src/assets/MorningSB.png
  client/src/assets/NightSB.png
  client/src/components/pages/home.tsx
  client/src/components/pages/signup.tsx
  client/src/components/pages/welcome.tsx
  client/src/css/App.css
  client/src/css/home.css
  client/src/css/signup.css
  client/src/css/welcome.css
Labels: enhancement

#69 Delete client/yarn.lock
  client/yarn.lock
Labels: optimization, security

#70 Store User Acc and Pw
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/pages/home.tsx
  client/src/components/pages/login.tsx
  client/src/components/pages/welcome.tsx
  client/src/components/utils/encryption.tsx
  client/src/components/utils/user-cred.tsx
  client/src/components/utils/user-utils.tsx
  client/src/css/App.css
Labels: enhancement, needs review

#73 Updates README
  README.md
  client/public/logo2048.png
  client/src/README.md
  server/src/README.md
Labels: documentation

#71 fixed music page css
  client/src/components/pages/music.tsx
  client/src/css/AlarmModal.css
  client/src/css/journal.css
  client/src/css/music.css
Labels: bug, needs review
